export default {
  CMS_API_DOMAIN: process.env.CMS_API_DOMAIN,
  CMS_API_TOKEN: process.env.CMS_API_TOKEN,
  CMS_PREVIEW_DOMAIN: process.env.CMS_PREVIEW_DOMAIN,
  CMS_PREVIEW_API_TOKEN: process.env.CMS_PREVIEW_API_TOKEN,
  CMS_SPACEID_SITE: process.env.CMS_SPACEID_SITE,
  CMS_ENV: "master",
  SENTRY_DSN: process.env.SENTRY_DSN,
  NOWLOGS_SECRET: process.env.NOWLOGS_SECRET,
};
